---
- name: "Import preflight tasks"
  ansible.builtin.import_tasks: "preflight.yml"

- name: "Import install tasks"
  when: "prometheus_proxy_state == 'present'"
  ansible.builtin.import_tasks: "install.yml"

- name: "Import uninstall tasks"
  when: "prometheus_proxy_state == 'absent'"
  ansible.builtin.import_tasks: "uninstall.yml"
